name: Auto QA Apply
on:
  pull_request:
    types: [opened, synchronized]

jobs:
  auto-apply-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Atlantis Plan
        run: sleep 30 

      - name: Comment Apply QA
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d "{\"body\": \"atlantis apply -p qa\"}"
