name: Release Docker image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: 286962625224.dkr.ecr.us-east-1.amazonaws.com/actions/hello
  CACHE_REGISTRY: 286962625224.dkr.ecr.us-east-1.amazonaws.com/actions/hello-cache

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yaml

  release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Declare some variables
        shell: bash
        run: |
          echo "GH_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::286962625224:role/gh-actions
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Release
        uses: docker/build-push-action@v6
        with:
          push: true
          target: release
          tags: |
            ${{ env.REGISTRY }}:${{ env.GH_SHA }}
            ${{ env.REGISTRY }}:${{ github.ref_name }}

      - name: Cache Update
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY }}:latest
          target: builder
          tags: |
            ${{ env.CACHE_REGISTRY }}:${{ env.GH_SHA }}
            ${{ env.CACHE_REGISTRY }}:${{ github.ref_name }}
            ${{ env.CACHE_REGISTRY }}:latest
